services:
  zdcrmapi:
    image: zdcrmapi
    build:
      context: apps/api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "dist/main.js"]
